### ISSUE TITLE
TypeError: navigator.getUserMedia is not a function

### ISSUE THREAD

**Issue by pratikbalar123** [WebDevSimplified/Face-Detection-JavaScript#9]
error in Firefox 

**TypeError: navigator.getUserMedia is not a function**

![Screenshot (280)](https://user-images.githubusercontent.com/41847153/66901741-e9933500-f01c-11e9-9ace-681293a2dd56.png)

**Comment by WebDevSimplified** [comment]
Try using navigator.mediaDevices.getUserMedia()

**Comment by pratikbalar123** [comment]
.... is not a function
![Screenshot (281)](https://user-images.githubusercontent.com/41847153/66924472-53750400-f048-11e9-9003-e768543e55d7.png)

**Comment by pratikbalar123** [comment]
i.m using Firefox 69 .but i also tried it in chrome (Chrome 77 on Windows 10) and .....
![Screenshot (283)](https://user-images.githubusercontent.com/41847153/66927527-938ab580-f04d-11e9-86b6-0d5bcae22a4b.png)

**Comment by souravgolui** [comment]
getUserMedia() is a promises so you have to use `.then()`

>>navigator.mediaDevices.getUserMedia().then((stream)=> {})

**Comment by WebDevSimplified** [comment]
You need to make sure you pass parameters to the `getUserMedia` function like I did in the code. That is why you are getting your first error.

**Comment by souravgolui** [comment]
` navigator.mediaDevices.getUserMedia({video: {}})
  .then((stream)=> {video.srcObject = stream;}, (err)=> console.error(err));`

**Comment by danielgeerts7** [comment]
> 
> 
> ` navigator.mediaDevices.getUserMedia({video: {}}) .then((stream)=> {video.srcObject = stream;}, (err)=> console.error(err));`

Had the same error in FireFox, and this fix worked for me!

**Comment by pratikbalar123** [comment]
working in chrome but still not working in firefox (v69.0.1).
![image](https://user-images.githubusercontent.com/41847153/69448772-4baf2a80-0d7f-11ea-97ea-eb9ddbf65f10.png)

**Comment by febriwidhawanto90** [comment]
You must have on secure context

The getUserMedia() method is only available in secure contexts. A secure context is one the browser is reasonably confident contains a document which was loaded securely, using HTTPS/TLS, and has limited exposure to insecure contexts. If a document isn't loaded in a secure context, the navigator.mediaDevices property is undefined, making access to getUserMedia() impossible.

Attempting to access getUserMedia() in this situation will result in a TypeError.

https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

**Comment by tulaibpirzada** [comment]
When I run the project on localhost it runs fine. But when I host it on my server instance then try to run it, then it gives this error. Any idea why its behaving like that?

**Comment by sapabapdev** [comment]
Chrome is requiring secure origins (HTTPS) for getUserMedia.

Starting with Chrome 47, getUserMedia() requests are only allowed from secure origins: HTTPS or localhost.

https://developers.google.com/web/updates/2015/10/chrome-47-webrtc?hl=en

**Comment by FotieMConstant** [comment]
> When I run the project on localhost it runs fine. But when I host it on my server instance then try to run it, then it gives this error. Any idea why its behaving like that?

are you on HTTPS? I mean the domain on your server? it should be on https for it to work.

**Comment by greatforu** [comment]
> > When I run the project on localhost it runs fine. But when I host it on my server instance then try to run it, then it gives this error. Any idea why its behaving like that?
> 
> are you on HTTPS? I mean the domain on your server? it should be on https for it to work.

My server is https but still not working and working fine on localhost
